### ISSUE TITLE
Add useful default templates

### ISSUE THREAD

**Issue by nhooyr** [gnormal/gnorm#104]
Would be nice to have some default templates.

**Comment by nhooyr** [comment]
Whoops we already do.

**Comment by natefinch** [comment]
https://github.com/gnormal/postgres-go  has some example templates.  I should update those with what we've been using at work.  They're a lot more extensive and useful.

**Comment by nhooyr** [comment]
That sounds great to me. We should link to those on the site. Otherwise I think for most users, no one will use gnorm because the setup time is too much and there are no examples listed so you aren't really sure what you get.

**Comment by nhooyr** [comment]
Would be nice to generate tests too.

**Comment by Oneymus** [comment]
Despite the absence of examples, I found the documentation to be exceptional for crafting my own templates. But, agreed, good examples can go a long way.

**Comment by freb** [comment]
I'm currently using xo, but I really like what I'm seeing with this project. Should I wait to kick the tires until the postgres templates are updated? Any timeline on that? Thanks for the fantastic work.

**Comment by natefinch** [comment]
I'll get the postgres templates updated asap. It's just a matter of copying
what we use at work.

**Comment by nhooyr** [comment]
Very excited 🎊

**Comment by natefinch** [comment]
https://github.com/gnormal/postgres-go

Just updated.

**Comment by natefinch** [comment]
note that a PR is about to land that adds support for other template languages.... a very simple example is at https://github.com/gnormal/jinja2-example

**Comment by nhooyr** [comment]
@natefinch the linked repository is inaccessible for me.

**Comment by natefinch** [comment]
refresh, I typoed the link

**Comment by natefinch** [comment]
it's at https://github.com/gnormal/jinja-example

**Comment by freb** [comment]
@natefinch, thanks for the update!

**Comment by nhooyr** [comment]
Going to close as it has been a long time and I'm not sure if this is relevant anymore.
