### ISSUE TITLE
compLess?

### ISSUE THREAD

**Issue by thoellrich** [gnormal/gnorm#15]
https://github.com/gnormal/gnorm/blob/3184e57c5fa439d8245c67f42c9af361b9a2c2d0/database/drivers/mysql/templates/schema.gotmpl#L33

Looks like a copy & paste error. Don't have enough time for a PR right now.

**Comment by natefinch** [comment]
ahh yep. Thanks... I swear I fixed that, but evidently not

**Comment by natefinch** [comment]
Thanks!  fixed with 4c1cac7927e94ef8e5271e0a52b13f94bf59ff4d

**Comment by thoellrich** [comment]
Thank you!
