### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by markbates** [gnormal/gnorm#32]
When I tried to install via `go get` I get an import error.

```
$ go get -u -v github.com/gnormal/gnorm 
github.com/gnormal/gnorm (download)
package github.com/gnormal/gnorm: code in directory /Users/markbates/Dropbox/development/gocode/src/github.com/gnormal/gnorm expects import "gnorm.org/gnorm"
```

**Comment by natefinch** [comment]
that's because you gotta `go get gnorm.org/gnorm` :)

**Comment by natefinch** [comment]
Hmm.. but I notice that I didn't say that anywhere in the readme.  Will make obvious :)

**Comment by markbates** [comment]
The README doesn’t say that. It just says that it’s Go gettable.

The README needs some instructions on tying it from there since it’s a vanity domain.

-----------
Mark Bates

**Comment by markbates** [comment]
Never mind. You beat me to the punch. :)

**Comment by natefinch** [comment]
Fixed! Thanks!
