### ISSUE TITLE
gnorm gen fails

### ISSUE THREAD

**Issue by gernest** [gnormal/gnorm#41]
With the latest master running gnorm gen  I get

```
$ gnorm gen
Error: generating file for schema Public: error writing generated file "Public.go
": cannot replace "Public.go" with tempfile "/var/folders/ft/j4yq82wd4bd4s74gvmv4n_000000gn/T/Public.go436637883": rename /var/folders/ft/j4yq82wd4bd4s74gvmv4n_000000gn/T/Public.go436637883 Public.go: cross-device link
Usage:
  gnorm gen [flags]

Flags:
  -c, --config string   relative path to gnorm config file (default "gnorm.toml")
  -h, --help            help for gen
  -v, --verbose         show debugging output
```

Somehow this part https://github.com/gnormal/gnorm/blob/9354db9b80938db07681cb45dd19b77c24f710be/run/generate.go#L130-L132 fails

**Comment by natefinch** [comment]
arg.  you must have your temp dir on a different disk than your output directory or something. 

I have code that writes the files to a temp file first and then renames it, to ensure the whole file gets written.  it's honestly overkill,and evidently buggy.

**Comment by gernest** [comment]
Have you thought about just using  `ioutil.WriteFile`?

There is no need to be fancy, since the whole point of generating files is just overwriting them.

**Comment by natefinch** [comment]
Yeah, I was going to go back to that. That's the way it was before.

**Comment by gernest** [comment]
Okay.

**Comment by natefinch** [comment]
if you want to fix it, you can search for atomic.Writefile and replace it with ioutil.writefile

**Comment by gernest** [comment]
Okay.
