### ISSUE TITLE
build with mage not working

### ISSUE THREAD

**Issue by joeblew99** [gnormal/gnorm#43]
maybe i am doing soemthing wrong ?

````
go get -u gnorm.org/gnorm

go get github.com/magefile/mage

cd /Users/apple/workspace/go/src/gnorm.org/gnorm && mage build
mage.go:11:2: could not import github.com/magefile/mage/mg (can't find import: "gnorm.org/gnorm/vendor/github.com/magefile/mage/mg")
make: *** [build] Error 1
````

**Comment by natefinch** [comment]
weird, I can reproduce on one machine and not another.  I'll look into it. For now, just doing go install for gnorm will work fine.. it just doesn't bake in the version info or the docs... which aren't critical

**Comment by natefinch** [comment]
a fix has been made to mage. Please update mage and retry.

**Comment by joeblew99** [comment]
works  - thank you !!


x-MacBook-Pro:gu-io apple$ go get -u gnorm.org/gnorm
x-MacBook-Pro:gu-io apple$ go get github.com/magefile/mage
x-MacBook-Pro:gu-io apple$ go get -u github.com/magefile/mage
