### ISSUE TITLE
Reference to run make.go is incorrect

### ISSUE THREAD

**Issue by rossnanop** [gnormal/gnorm#47]
In various places, 
https://github.com/gnormal/gnorm/blob/master/CONTRIBUTING.md
https://github.com/gnormal/gnorm/blob/master/site/content/getting-started/_index.md
it calls to `go run $GOPATH/src/gnorm.org/gnorm/make.go` but there is no make.go anywhere in the project.

My guess is I should be using mage to build? Or running `go run $GOPATH/src/gnorm.org/gnorm/main.go` in the cases it tells me to check the binary builds.

Happy to submit a PR to update the documentation with either update.

**Comment by natefinch** [comment]
Ahh yes, it should be using mage to build now.  A PR would be welcome :)
