### ISSUE TITLE
"index" template function shadows built-in function

### ISSUE THREAD

**Issue by tarqe39** [gnormal/gnorm#95]
Hi,

it seems that custom "index" function overrides golang template "index" function for accessing slice elements. Maybe a rename would be OK solution?

**Comment by natefinch** [comment]
Hmm, yes, absolutely a problem. I have a PR up that namespaces the string
functions, that'll fox it. I'll get that landed ASAP.

**Comment by natefinch** [comment]
Fixed with #106
